use_frameworks!

platform :ios, '13.0'

target 'JLHaoWabLib_Example' do
  pod 'JLHaoWabLib', :path => '../'

  target 'JLHaoWabLib_Tests' do
    inherit! :search_paths

    
    
    
    
    pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    end
      
  end
end
